name: reviewdog
on: [pull_request]

jobs:
  staticcheck:
    timeout-minutes: 30
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: staticcheck
        uses: reviewdog/action-staticcheck@v1
        with:
          reporter: github-pr-review
          level: warning

  misspell:
    timeout-minutes: 30
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          reporter: github-pr-review
          level: warning
          locale: "US"

  actionlint:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
